version: '3.8'

services:
  prometheus:
    build:
      context: ./DockerFile
      dockerfile: DockerFile
    container_name: prometheus
    volumes:
      - $PROMETHEUS_YML:/etc/prometheus/prometheus.yml.template:ro
      - $PROMETHEUS_TARGET:/etc/prometheus/targets:ro
      - $PROMETHEUS_RULE:/etc/prometheus/rules:ro
      - prometheus_data:/prometheus
    environment:
      - NODA_PATH_TARGET=${NODA_PATH_TARGET}
      - MYSQL_PATH_TARGET=${MYSQL_PATH_TARGET}
      - BLACKBOX_PATH_TARGET=${BLACKBOX_PATH_TARGET}
      - NODA_PATH_RULES=${NODA_PATH_RULES}
      - MYSQL_PATH_RULES=${MYSQL_PATH_RULES}
      - BLACKBOX_PATH_RULES=${BLACKBOX_PATH_RULES}
    ports:
      - "$PROMETHEUS_PORT:9090"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:9090/-/healthy || exit 1"]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 40s
    networks:
      - monitoring
      - grafana_prometheus
      - vm_network
      - monitor_app

  alertmanager-config:
    image: alpine:3.20
    command: >
      sh -c "apk add --no-cache gettext &&
             envsubst < /config/alertmanager.yml.tpl > /shared/alertmanager.yml"
    volumes:
      - ./alertmanager/alertmanager.yml.tpl:/config/alertmanager.yml.tpl:ro
      - alertmanager-config:/shared
    environment:
      - TOKEN=${TOKEN}

  alertmanager:
    depends_on:
      alertmanager-config:
        condition: service_completed_successfully
    image: $ALERT_IMAGE
    container_name: alertmanager
    restart: always
    volumes:
      - alertmanager_data:/alertmanager
      - alertmanager-config:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    ports:
      - "$ALERT_PORT:9093"
    networks:
      - monitoring

  node_exporter:
    image: $NODA_IMAGE
    container_name: node_exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
    ports:
      - "$NODA_PORT:9100"
    networks:
      - monitoring


  blackbox_exporter:
    image: $BLACKBOX_IMAGE
    container_name: blackbox-exporter
    restart: always
    networks:
      - monitoring


  mysql_exporter:
    image: $MYSQL_IMAGE
    container_name: mysqld-exporter
    restart: always
    volumes:
      - $MYSQL_NDWORK:/.my.cnf:ro
    command:
      - "--config.my-cnf=/.my.cnf"
    networks:
      - monitoring
      - monitor_app

networks:
  monitoring:
    name: monitoring
    driver: bridge

  grafana_prometheus:
    name: grafana_prometheus
    driver: bridge

  vm_network:
    name: vm_network
    external: true

  monitor_app:
    name: monitor_app
    external: true

volumes:
  prometheus_data:
  alertmanager_data:
  alertmanager-config:



