global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "prod"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "/etc/prometheus/node-exporter/node-exporter.yml"
  - "/etc/prometheus/mysql/mysql-exporter.yml"
  - "/etc/prometheus/blackbox/blackbox.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    file_sd_configs:
      - files:
          - "/etc/prometheus/targets/node-exporter/node-exporter.yml"
        refresh_interval: 30s

  - job_name: "mysql-exporter"
    file_sd_configs:
      - files:
          - "/etc/prometheus/targets/mysql/mysql-exporter.yml"
        refresh_interval: 30s

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    scrape_interval: 30s
    file_sd_configs:
      - files:
          - "/etc/prometheus/targets/blackbox/blackbox.yml"
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115