groups:
  - name: mysql_exporter
    rules:
      - alert: MySQLDown
        expr: mysql_up == 0
        for: 1m
        labels:
          severity: critical
          service: mysql_exporter
        annotations:
          summary: "MySQL недоступен на {{ $labels.instance }}"