# Dockerfile
# ---- Stage 1: скачиваем готовый статический бинарник envsubst ----
FROM alpine:3.20 AS envsubst-builder

RUN apk add --no-cache curl \
    && curl -L -o /usr/local/bin/envsubst \
       "https://github.com/a8m/envsubst/releases/download/v1.4.3/envsubst-Linux-x86_64" \
    && chmod +x /usr/local/bin/envsubst

# ---- Stage 2: финальный образ на базе prometheus ----
FROM prom/prometheus:v3.4.1

COPY --from=envsubst-builder /usr/local/bin/envsubst /bin/envsubst
COPY entrypoint.sh /entrypoint.sh

USER root
RUN chmod +x /entrypoint.sh /bin/envsubst

ENTRYPOINT ["/entrypoint.sh"]